---
http_interactions:
- request:
    method: post
    uri: http://api.brightbox.dev/token
    body:
      encoding: UTF-8
      string: '{"grant_type":"password","username":"jason.null@brightbox.com","password":"N:B3e%7Cmh"}'
    headers:
      User-Agent:
      - fog-core/1.32.1
      Authorization:
      - Basic YXBwLTEyMzQ1Om1vY2J1aXBiaWFhNms2Yw==
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Cache-Control:
      - no-store
      X-Oauth-Scopes:
      - infrastructure, orbit
      Content-Length:
      - '190'
      X-Content-Type-Options:
      - nosniff
      X-Ua-Compatible:
      - IE=Edge
      Etag:
      - '"46fbbfb8a2a2a7ac18ddeb0827caecd5"'
      X-Request-Id:
      - f023fab1e85e0bfa6dd2047ba00a56e2
      X-Runtime:
      - '0.089060'
      Server:
      - WEBrick/1.3.1 (Ruby/1.9.3/2014-11-13)
      Date:
      - Wed, 30 Sep 2015 14:34:22 GMT
      Connection:
      - Keep-Alive
    body:
      encoding: UTF-8
      string: '{"access_token":"64f68b5dddea1c6b774286180375ba883b896cac","token_type":"Bearer","refresh_token":"b7716ed2480d2831c8cb8af8ea536666c27815b1","scope":"infrastructure,
        orbit","expires_in":7200}'
    http_version: 
  recorded_at: Wed, 30 Sep 2015 14:34:22 GMT
- request:
    method: get
    uri: http://api.brightbox.dev/1.0/accounts
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - fog-core/1.32.1
      Authorization:
      - Bearer 64f68b5dddea1c6b774286180375ba883b896cac
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      X-Oauth-Scopes:
      - infrastructure, orbit
      Content-Type:
      - application/json; charset=utf-8
      X-Ua-Compatible:
      - IE=Edge
      Etag:
      - '"79022220a299b096df8561e8b08c2a6c"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - d9bf84944cdefeb0ad6eec2208adb07b
      X-Runtime:
      - '0.115969'
      Server:
      - WEBrick/1.3.1 (Ruby/1.9.3/2014-11-13)
      Date:
      - Wed, 30 Sep 2015 14:34:22 GMT
      Content-Length:
      - '1611'
      Connection:
      - Keep-Alive
    body:
      encoding: UTF-8
      string: '[{"id":"acc-12345","resource_type":"account","url":"https://api.gb1.brightbox.com/1.0/accounts/acc-12345","name":"CLI
        test account","status":"active","ram_limit":3200000,"ram_used":0,"dbs_ram_limit":32768,"dbs_ram_used":0,"cloud_ips_limit":32,"cloud_ips_used":0,"load_balancers_limit":5,"load_balancers_used":0,"clients":[{"id":"cli-12345","resource_type":"api_client","url":"https://api.gb1.brightbox.com/1.0/api_clients/cli-12345","name":"CLI
        test API client","description":"","revoked_at":null,"permissions_group":"full"}],"images":[],"servers":[],"load_balancers":[],"database_servers":[],"database_snapshots":[],"cloud_ips":[],"server_groups":[{"id":"grp-12345","resource_type":"server_group","url":"https://api.gb1.brightbox.com/1.0/server_groups/grp-12345","name":"default","description":"All
        new servers are added to this group unless specified otherwise.","created_at":"2015-09-29T08:22:15Z","default":true}],"firewall_policies":[{"id":"fwp-12345","resource_type":"firewall_policy","url":"https://api.gb1.brightbox.com/1.0/firewall_policies/fwp-12345","default":true,"name":"default","created_at":"2015-09-29T08:22:15Z","description":"Applied
        to the default server group."}],"owner":{"id":"usr-12345","resource_type":"user","url":"https://api.gb1.brightbox.com/1.0/users/usr-12345","name":"Jason
        Null","email_address":"jason.null@brightbox.com"},"users":[],"zones":[{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-a"},{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-b"}]}]'
    http_version: 
  recorded_at: Wed, 30 Sep 2015 14:34:22 GMT
- request:
    method: post
    uri: http://api.brightbox.dev/token
    body:
      encoding: UTF-8
      string: '{"grant_type":"refresh_token","refresh_token":"b7716ed2480d2831c8cb8af8ea536666c27815b1"}'
    headers:
      User-Agent:
      - fog-core/1.32.1
      Authorization:
      - Basic YXBwLTEyMzQ1Om1vY2J1aXBiaWFhNms2Yw==
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Cache-Control:
      - no-store
      X-Oauth-Scopes:
      - infrastructure, orbit
      Content-Length:
      - '190'
      X-Content-Type-Options:
      - nosniff
      X-Ua-Compatible:
      - IE=Edge
      Etag:
      - '"dd8fd24413fcd0a0a60481951e332374"'
      X-Request-Id:
      - e937501889b560dac744be408f920d6b
      X-Runtime:
      - '0.044393'
      Server:
      - WEBrick/1.3.1 (Ruby/1.9.3/2014-11-13)
      Date:
      - Wed, 30 Sep 2015 14:34:22 GMT
      Connection:
      - Keep-Alive
    body:
      encoding: UTF-8
      string: '{"access_token":"c8975689c865aafc885cf964a76fa72418451e25","token_type":"Bearer","refresh_token":"9f7921dbea20637a80b117f3e677060831b6522d","scope":"infrastructure,
        orbit","expires_in":7200}'
    http_version: 
  recorded_at: Wed, 30 Sep 2015 14:34:22 GMT
- request:
    method: get
    uri: http://api.brightbox.dev/1.0/accounts
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - fog-core/1.32.1
      Authorization:
      - Bearer c8975689c865aafc885cf964a76fa72418451e25
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      X-Oauth-Scopes:
      - infrastructure, orbit
      Content-Type:
      - application/json; charset=utf-8
      X-Ua-Compatible:
      - IE=Edge
      Etag:
      - '"79022220a299b096df8561e8b08c2a6c"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - a1371291bf1482c522f967fff0d1b86f
      X-Runtime:
      - '0.044154'
      Server:
      - WEBrick/1.3.1 (Ruby/1.9.3/2014-11-13)
      Date:
      - Wed, 30 Sep 2015 14:34:22 GMT
      Content-Length:
      - '1611'
      Connection:
      - Keep-Alive
    body:
      encoding: UTF-8
      string: '[{"id":"acc-12345","resource_type":"account","url":"https://api.gb1.brightbox.com/1.0/accounts/acc-12345","name":"CLI
        test account","status":"active","ram_limit":3200000,"ram_used":0,"dbs_ram_limit":32768,"dbs_ram_used":0,"cloud_ips_limit":32,"cloud_ips_used":0,"load_balancers_limit":5,"load_balancers_used":0,"clients":[{"id":"cli-12345","resource_type":"api_client","url":"https://api.gb1.brightbox.com/1.0/api_clients/cli-12345","name":"CLI
        test API client","description":"","revoked_at":null,"permissions_group":"full"}],"images":[],"servers":[],"load_balancers":[],"database_servers":[],"database_snapshots":[],"cloud_ips":[],"server_groups":[{"id":"grp-12345","resource_type":"server_group","url":"https://api.gb1.brightbox.com/1.0/server_groups/grp-12345","name":"default","description":"All
        new servers are added to this group unless specified otherwise.","created_at":"2015-09-29T08:22:15Z","default":true}],"firewall_policies":[{"id":"fwp-12345","resource_type":"firewall_policy","url":"https://api.gb1.brightbox.com/1.0/firewall_policies/fwp-12345","default":true,"name":"default","created_at":"2015-09-29T08:22:15Z","description":"Applied
        to the default server group."}],"owner":{"id":"usr-12345","resource_type":"user","url":"https://api.gb1.brightbox.com/1.0/users/usr-12345","name":"Jason
        Null","email_address":"jason.null@brightbox.com"},"users":[],"zones":[{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-a"},{"id":"zon-12345","resource_type":"zone","url":"https://api.gb1.brightbox.com/1.0/zones/zon-12345","handle":"gb1-b"}]}]'
    http_version: 
  recorded_at: Wed, 30 Sep 2015 14:34:22 GMT
recorded_with: VCR 2.5.0
